# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.srcs/sources_1/bd/system/ip/system_axi_sc_0/system_axi_sc_0.xci
# IP: The module: 'system_axi_sc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/bd_0cf0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_1/bd_0cf0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_2/bd_0cf0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_3/bd_0cf0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_4/bd_0cf0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_5/bd_0cf0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_6/bd_0cf0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_7/bd_0cf0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_8/bd_0cf0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_9/bd_0cf0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_10/bd_0cf0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_11/bd_0cf0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_12/bd_0cf0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_1/bd_0cf0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_5/bd_0cf0_s00a2s_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_6/bd_0cf0_sarn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_7/bd_0cf0_srn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_8/bd_0cf0_sawn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_9/bd_0cf0_swn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_10/bd_0cf0_sbn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_11/bd_0cf0_m00s2a_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_sc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_sc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.srcs/sources_1/bd/system/ip/system_axi_sc_0/system_axi_sc_0.xci
# IP: The module: 'system_axi_sc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/bd_0cf0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_1/bd_0cf0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_2/bd_0cf0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_3/bd_0cf0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_4/bd_0cf0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_5/bd_0cf0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_6/bd_0cf0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_7/bd_0cf0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_8/bd_0cf0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_9/bd_0cf0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_10/bd_0cf0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_11/bd_0cf0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_12/bd_0cf0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_1/bd_0cf0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_5/bd_0cf0_s00a2s_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_6/bd_0cf0_sarn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_7/bd_0cf0_srn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_8/bd_0cf0_sawn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_9/bd_0cf0_swn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_10/bd_0cf0_sbn_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/bd_0/ip/ip_11/bd_0cf0_m00s2a_0_ooc.xdc

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_sc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_axi_sc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_sc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
