# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.srcs/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xci
# IP: The module: 'system_zynq_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.srcs/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xci
# IP: The module: 'system_zynq_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
