"""
gen_test_vectors.py — Generate exact test vectors from golden model.

Runs the Board A and Board B golden models with deterministic inputs,
captures every intermediate value, and writes hex/CSV files that
RTL testbenches can load with $readmemh or compare against.

Usage:
    python gen_test_vectors.py

Output goes to golden_model/vectors/ directory.
"""
import os, json
from common import (
    NUM_SYMBOLS, MASK_16, MASK_32, MASK_128,
    MsgType, FillStatus, Regime, SIDE_BUY, SIDE_SELL,
    QuoteFrame, OrderFrame, FillFrame, frame_type,
    q16, from_q16, sext32,
    default_init_mids, default_init_spreads, default_sector_ids,
)
from board_a import BoardA
from board_b import BoardB


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)


def hex128(val):
    return f"{val & MASK_128:032X}"


def hex32(val):
    return f"{val & MASK_32:08X}"


def main():
    out_dir = os.path.join(os.path.dirname(__file__), "vectors")
    ensure_dir(out_dir)

    # ──────────────────────────────────────────────────────────
    # 1. msg_demux vectors: raw frames → expected routing
    # ──────────────────────────────────────────────────────────
    print("=== Generating msg_demux vectors ===")
    demux_vectors = []

    # Generate some real quote frames from Board A
    board_a = BoardA(num_sym=4, num_sectors=4)
    board_a.configure(
        regime=Regime.CALM, quote_interval=0, seed=0xDEAD_BEEF,
        init_mid=[q16(180.0), q16(420.0), q16(900.0), q16(115.0)],
        init_spread=[q16(0.10), q16(0.15), q16(0.25), q16(0.08)],
        sector_ids=[0, 0, 1, 1],
        active_count=4,
    )
    board_a.start()

    for cyc in range(20):
        bits = board_a.step(cyc)
        if bits is not None:
            mt = frame_type(bits)
            if mt == MsgType.QUOTE:
                qf = QuoteFrame.from_bits(bits)
                demux_vectors.append({
                    "cycle": cyc,
                    "frame_hex": hex128(bits),
                    "msg_type": "QUOTE",
                    "symbol": qf.symbol,
                    "regime": qf.regime,
                    "bid_hex": hex32(qf.bid),
                    "ask_hex": hex32(qf.ask),
                    "bid_size": qf.bid_size,
                    "ask_size": qf.ask_size,
                    "seq_num": qf.seq_num,
                    "expected_route": "quote",
                })

    # Generate a fill frame
    order = OrderFrame(symbol=0, side=SIDE_BUY, price=q16(200.0),
                       qty=100, order_id=1, timestamp=42)
    fill_bits = board_a.step(20, order_in=order)
    if fill_bits is not None:
        ff = FillFrame.from_bits(fill_bits)
        demux_vectors.append({
            "cycle": 20,
            "frame_hex": hex128(fill_bits),
            "msg_type": "FILL",
            "symbol": ff.symbol,
            "side": ff.side,
            "status": ff.status,
            "fill_price_hex": hex32(ff.fill_price),
            "fill_qty": ff.fill_qty,
            "order_id": ff.order_id,
            "ts_echo": ff.ts_echo,
            "expected_route": "fill",
        })

    # Add some invalid frame types for error path
    for bad_type in [0x0, 0x2, 0x4, 0x5, 0xF]:
        bad_frame = bad_type << 124 | 0x0DEADBEEFCAFE1234567890AB
        demux_vectors.append({
            "cycle": -1,
            "frame_hex": hex128(bad_frame),
            "msg_type": f"INVALID_0x{bad_type:X}",
            "expected_route": "error",
        })

    with open(os.path.join(out_dir, "demux_vectors.json"), "w") as f:
        json.dump(demux_vectors, f, indent=2)

    # Write hex file for $readmemh (just the 128-bit frames)
    with open(os.path.join(out_dir, "demux_frames.hex"), "w") as f:
        f.write("// msg_demux test frames — generated by gen_test_vectors.py\n")
        f.write("// Each line is a 128-bit frame in hex (32 hex digits)\n")
        for v in demux_vectors:
            f.write(f"{v['frame_hex']}  // {v['msg_type']} {v.get('expected_route','')}\n")

    print(f"  {len(demux_vectors)} demux vectors written")

    # ──────────────────────────────────────────────────────────
    # 2. quote_book vectors: quote frames → stored bid/ask
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating quote_book vectors ===")
    from board_b import QuoteBook
    book = QuoteBook(num_sym=4)
    qb_vectors = []

    # Reuse first few quote frames from Board A
    board_a2 = BoardA(num_sym=4, num_sectors=4)
    board_a2.configure(
        regime=Regime.CALM, quote_interval=0, seed=0xDEAD_BEEF,
        init_mid=[q16(180.0), q16(420.0), q16(900.0), q16(115.0)],
        init_spread=[q16(0.10), q16(0.15), q16(0.25), q16(0.08)],
        sector_ids=[0, 0, 1, 1],
        active_count=4,
    )
    board_a2.start()

    for cyc in range(30):
        bits = board_a2.step(cyc)
        if bits is not None and frame_type(bits) == MsgType.QUOTE:
            qf = QuoteFrame.from_bits(bits)
            book.update(qf)
            qb_vectors.append({
                "cycle": cyc,
                "frame_hex": hex128(bits),
                "symbol": qf.symbol,
                "regime": qf.regime,
                "bid_hex": hex32(qf.bid),
                "ask_hex": hex32(qf.ask),
                "bid_size": qf.bid_size,
                "ask_size": qf.ask_size,
                "stored_bid_hex": [hex32(book.bid[i]) for i in range(4)],
                "stored_ask_hex": [hex32(book.ask[i]) for i in range(4)],
            })

    with open(os.path.join(out_dir, "quote_book_vectors.json"), "w") as f:
        json.dump(qb_vectors, f, indent=2)
    print(f"  {len(qb_vectors)} quote_book vectors written")

    # ──────────────────────────────────────────────────────────
    # 3. feature_compute vectors: mid/ema/deviation per quote
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating feature_compute vectors ===")
    from board_b import FeatureEngine
    feat = FeatureEngine(num_sym=4)
    alpha = 6554  # ~10% smoothing
    fc_vectors = []

    book2 = QuoteBook(num_sym=4)
    board_a3 = BoardA(num_sym=4, num_sectors=4)
    board_a3.configure(
        regime=Regime.CALM, quote_interval=0, seed=0xDEAD_BEEF,
        init_mid=[q16(180.0), q16(420.0), q16(900.0), q16(115.0)],
        init_spread=[q16(0.10), q16(0.15), q16(0.25), q16(0.08)],
        sector_ids=[0, 0, 1, 1],
        active_count=4,
    )
    board_a3.start()

    for cyc in range(40):
        bits = board_a3.step(cyc)
        if bits is not None and frame_type(bits) == MsgType.QUOTE:
            qf = QuoteFrame.from_bits(bits)
            book2.update(qf)
            mid = qf.mid
            deviation = feat.compute(qf.symbol, mid, alpha)
            fc_vectors.append({
                "cycle": cyc,
                "frame_hex": hex128(bits),
                "symbol": qf.symbol,
                "bid_hex": hex32(qf.bid),
                "ask_hex": hex32(qf.ask),
                "mid_hex": hex32(mid),
                "ema_hex": hex32(feat.ema[qf.symbol]),
                "deviation_hex": hex32(deviation),
                "deviation_signed": sext32(deviation),
                "initialized": feat.initialized[qf.symbol],
                "alpha": alpha,
            })

    with open(os.path.join(out_dir, "feature_compute_vectors.json"), "w") as f:
        json.dump(fc_vectors, f, indent=2)
    print(f"  {len(fc_vectors)} feature_compute vectors written")

    # ──────────────────────────────────────────────────────────
    # 4. Full pipeline vectors: Board B end-to-end
    #    quote → quote_book → feature → strategy → risk → order
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating full pipeline vectors ===")
    board_b = BoardB(num_sym=4)
    board_b.ema_alpha = alpha
    board_b.threshold = q16(0.50)  # $0.50 threshold
    board_b.base_qty = 100
    board_b.max_position = 500
    board_b.max_order_rate = 1000
    board_b.max_loss = 100  # integer dollars (matches total_pnl = cash >> 16)
    board_b.start()

    board_a4 = BoardA(num_sym=4, num_sectors=4)
    board_a4.configure(
        regime=Regime.CALM, quote_interval=0, seed=0xDEAD_BEEF,
        init_mid=[q16(180.0), q16(420.0), q16(900.0), q16(115.0)],
        init_spread=[q16(0.10), q16(0.15), q16(0.25), q16(0.08)],
        sector_ids=[0, 0, 1, 1],
        active_count=4,
    )
    board_a4.start()

    pipeline_vectors = []
    for cyc in range(100):
        bits = board_a4.step(cyc)
        if bits is not None:
            mt = frame_type(bits)
            order_bits = board_b.step(cyc, bits)

            entry = {
                "cycle": cyc,
                "frame_in_hex": hex128(bits),
                "msg_type": "QUOTE" if mt == MsgType.QUOTE else "FILL" if mt == MsgType.FILL else f"0x{mt:X}",
            }

            if mt == MsgType.QUOTE:
                qf = QuoteFrame.from_bits(bits)
                entry["symbol"] = qf.symbol
                entry["bid_hex"] = hex32(qf.bid)
                entry["ask_hex"] = hex32(qf.ask)
                entry["mid_hex"] = hex32(qf.mid)
                entry["ema_hex"] = hex32(board_b.features.ema[qf.symbol])
                entry["quotes_rcvd"] = board_b.quotes_rcvd

            if order_bits is not None:
                of = OrderFrame.from_bits(order_bits)
                entry["order_out_hex"] = hex128(order_bits)
                entry["order_symbol"] = of.symbol
                entry["order_side"] = "BUY" if of.side == SIDE_BUY else "SELL"
                entry["order_price_hex"] = hex32(of.price)
                entry["order_qty"] = of.qty
                entry["order_id"] = of.order_id
                entry["orders_sent"] = board_b.orders_sent

            pipeline_vectors.append(entry)

    with open(os.path.join(out_dir, "pipeline_vectors.json"), "w") as f:
        json.dump(pipeline_vectors, f, indent=2)
    print(f"  {len(pipeline_vectors)} pipeline vectors written")

    # ──────────────────────────────────────────────────────────
    # 5. position_tracker vectors: fill processing
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating position_tracker vectors ===")
    from board_b import PositionTracker
    pt = PositionTracker(num_sym=4)
    pt_vectors = []

    fills = [
        FillFrame(symbol=0, side=SIDE_BUY,  status=FillStatus.FILLED,
                  fill_price=q16(180.05), fill_qty=100, order_id=0, ts_echo=10),
        FillFrame(symbol=1, side=SIDE_SELL, status=FillStatus.FILLED,
                  fill_price=q16(420.10), fill_qty=50,  order_id=1, ts_echo=20),
        FillFrame(symbol=0, side=SIDE_SELL, status=FillStatus.FILLED,
                  fill_price=q16(181.00), fill_qty=100, order_id=2, ts_echo=30),
        FillFrame(symbol=2, side=SIDE_BUY,  status=FillStatus.REJECTED,
                  fill_price=0,           fill_qty=0,   order_id=3, ts_echo=40),
        FillFrame(symbol=0, side=SIDE_BUY,  status=FillStatus.FILLED,
                  fill_price=q16(179.50), fill_qty=200, order_id=4, ts_echo=50),
    ]

    for i, fill in enumerate(fills):
        pt.process_fill(fill)
        pt_vectors.append({
            "step": i,
            "fill_frame_hex": hex128(fill.to_bits()),
            "symbol": fill.symbol,
            "side": "BUY" if fill.side == SIDE_BUY else "SELL",
            "status": "FILLED" if fill.is_filled else "REJECTED",
            "fill_price_hex": hex32(fill.fill_price),
            "fill_qty": fill.fill_qty,
            "positions": [hex32(pt.position[j]) for j in range(4)],
            "cash_hex": f"{pt.cash & MASK_128:012X}",
            "total_pnl": pt.total_pnl,
            "fills_rcvd": pt.fills_rcvd,
        })

    with open(os.path.join(out_dir, "position_tracker_vectors.json"), "w") as f:
        json.dump(pt_vectors, f, indent=2)
    print(f"  {len(pt_vectors)} position_tracker vectors written")

    # ──────────────────────────────────────────────────────────
    # 6. strategy_engine vectors: deviation → trade signal
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating strategy_engine vectors ===")
    from board_b import Strategy
    strat_vectors = []
    threshold = q16(0.50)  # $0.50
    base_qty = 100

    test_cases = [
        # (deviation, bid, ask, description)
        (q16(0.0),   q16(180.0), q16(180.10), "no deviation → no trade"),
        (q16(0.30),  q16(180.0), q16(180.10), "small positive → no trade"),
        (q16(0.51),  q16(180.0), q16(180.10), "above threshold → SELL at bid"),
        (q16(1.00),  q16(180.0), q16(180.10), "large positive → SELL at bid"),
        # Negative deviation as unsigned Q16.16 (two's complement)
        (((-q16(0.30)) & MASK_32), q16(180.0), q16(180.10), "small negative → no trade"),
        (((-q16(0.51)) & MASK_32), q16(180.0), q16(180.10), "below -threshold → BUY at ask"),
        (((-q16(2.00)) & MASK_32), q16(180.0), q16(180.10), "large negative → BUY at ask"),
        (q16(0.50),  q16(180.0), q16(180.10), "exactly at threshold → no trade"),
        (((-q16(0.50)) & MASK_32), q16(180.0), q16(180.10), "exactly at -threshold → no trade"),
    ]

    for dev, bid, ask, desc in test_cases:
        result = Strategy.evaluate(dev, bid, ask, threshold, base_qty)
        entry = {
            "description": desc,
            "deviation_hex": hex32(dev),
            "deviation_signed": sext32(dev),
            "bid_hex": hex32(bid),
            "ask_hex": hex32(ask),
            "threshold_hex": hex32(threshold),
            "base_qty": base_qty,
        }
        if result is not None:
            entry["signal_valid"] = True
            entry["signal_side"] = "BUY" if result.side == SIDE_BUY else "SELL"
            entry["signal_price_hex"] = hex32(result.price)
            entry["signal_qty"] = result.qty
        else:
            entry["signal_valid"] = False
        strat_vectors.append(entry)

    with open(os.path.join(out_dir, "strategy_vectors.json"), "w") as f:
        json.dump(strat_vectors, f, indent=2)
    print(f"  {len(strat_vectors)} strategy vectors written")

    # ──────────────────────────────────────────────────────────
    # 7. latency_histogram vectors
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating latency_histogram vectors ===")
    from board_b import LatencyStats
    lat = LatencyStats()
    lat_vectors = []

    latency_samples = [
        (10, 50),    # latency = 40
        (100, 164),  # latency = 64
        (200, 205),  # latency = 5
        (300, 332),  # latency = 32
        (400, 496),  # latency = 96
        (500, 531),  # latency = 31
        (600, 600),  # latency = 0
        (700, 763),  # latency = 63
    ]

    for ts_echo, current_cycle in latency_samples:
        lat.record(ts_echo, current_cycle)
        latency = (current_cycle - ts_echo) & MASK_16
        lat_vectors.append({
            "ts_echo": ts_echo,
            "current_cycle": current_cycle,
            "latency": latency,
            "bin_idx": min(latency >> 5, 15),
            "lat_min": lat.lat_min,
            "lat_max": lat.lat_max,
            "lat_sum": lat.lat_sum,
            "lat_count": lat.lat_count,
            "histogram": list(lat.hist),
        })

    with open(os.path.join(out_dir, "latency_histogram_vectors.json"), "w") as f:
        json.dump(lat_vectors, f, indent=2)
    print(f"  {len(lat_vectors)} latency vectors written")

    # ──────────────────────────────────────────────────────────
    # 8. Board A LFSR vectors: multiple seeds, 16 steps each
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating Board A LFSR vectors ===")
    from common import LFSR32 as LFSR32_cls
    lfsr_vectors = {}
    for seed_name, seed_val in [("0xDEADBEEF", 0xDEADBEEF), ("0x00000001", 1), ("0x00000000", 0)]:
        lfsr = LFSR32_cls(seed_val)
        eff = lfsr.value
        steps = [lfsr.step() for _ in range(16)]
        lfsr_vectors[seed_name] = {"effective_seed": hex32(eff), "steps": [hex32(v) for v in steps]}
    with open(os.path.join(out_dir, "lfsr_vectors.json"), "w") as f:
        json.dump(lfsr_vectors, f, indent=2)
    print(f"  LFSR vectors for 3 seeds written")

    # ──────────────────────────────────────────────────────────
    # 9. Board A noise vectors: 4 symbols, 8 ticks
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating Board A noise vectors ===")
    from board_a import NoiseGen
    noise = NoiseGen(num_sym=4, num_sectors=4)
    noise.seed(0xDEADBEEF)
    sector_ids_nv = [0, 0, 1, 1]
    noise_vectors = []
    for tick in range(8):
        step_out = noise.generate(active_count=4, sector_ids=sector_ids_nv)
        noise_vectors.append({
            "tick": tick,
            "step_out": [hex32(step_out[s] & MASK_32) for s in range(4)],
        })
    with open(os.path.join(out_dir, "noise_vectors.json"), "w") as f:
        json.dump(noise_vectors, f, indent=2)
    print(f"  {len(noise_vectors)} noise vectors written")

    # ──────────────────────────────────────────────────────────
    # 10. Board A quote frame vectors: 16 quotes
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating Board A quote vectors ===")
    board_a_qv = BoardA(num_sym=4, num_sectors=4)
    board_a_qv.configure(
        regime=Regime.CALM, quote_interval=0, seed=0xDEAD_BEEF,
        init_mid=[q16(180.0), q16(420.0), q16(900.0), q16(115.0)],
        init_spread=[q16(0.10), q16(0.15), q16(0.25), q16(0.08)],
        sector_ids=[0, 0, 1, 1],
        active_count=4,
    )
    board_a_qv.start()
    quote_vectors = []
    for cyc in range(16):
        bits = board_a_qv.step(cyc)
        if bits is not None and frame_type(bits) == MsgType.QUOTE:
            qf = QuoteFrame.from_bits(bits)
            quote_vectors.append({
                "cycle": cyc,
                "frame_hex": hex128(bits),
                "symbol": qf.symbol,
                "regime": qf.regime,
                "bid_hex": hex32(qf.bid),
                "ask_hex": hex32(qf.ask),
                "seq_num": qf.seq_num,
            })
    with open(os.path.join(out_dir, "quote_vectors.json"), "w") as f:
        json.dump(quote_vectors, f, indent=2)
    with open(os.path.join(out_dir, "quote_frames.hex"), "w") as f:
        for v in quote_vectors:
            f.write(f"{v['frame_hex']}\n")
    print(f"  {len(quote_vectors)} quote vectors written")

    # ──────────────────────────────────────────────────────────
    # 11. Board A exchange vectors: 6 test orders
    # ──────────────────────────────────────────────────────────
    print("\n=== Generating Board A exchange vectors ===")
    from board_a import Exchange as Exchange_cls
    bid = [board_a_qv.market.best_bid[s] for s in range(4)]
    ask = [board_a_qv.market.best_ask[s] for s in range(4)]
    exchange = Exchange_cls(num_sym=4)
    test_orders_ev = [
        ("BUY at ask (fill)", OrderFrame(symbol=0, side=SIDE_BUY, price=ask[0], qty=100, order_id=0, timestamp=100)),
        ("BUY below ask (rej)", OrderFrame(symbol=0, side=SIDE_BUY, price=ask[0]-1, qty=50, order_id=1, timestamp=101)),
        ("SELL at bid (fill)", OrderFrame(symbol=1, side=SIDE_SELL, price=bid[1], qty=75, order_id=2, timestamp=102)),
        ("SELL above bid (rej)", OrderFrame(symbol=1, side=SIDE_SELL, price=bid[1]+1, qty=25, order_id=3, timestamp=103)),
        ("OORange sym=4 (rej)", OrderFrame(symbol=4, side=SIDE_BUY, price=q16(200.0), qty=10, order_id=4, timestamp=104)),
        ("BUY sym=3 (fill)", OrderFrame(symbol=3, side=SIDE_BUY, price=ask[3]+q16(1.0), qty=200, order_id=5, timestamp=105)),
    ]
    exchange_vectors = []
    for desc, order in test_orders_ev:
        fill = exchange.match(order, bid, ask)
        exchange_vectors.append({
            "description": desc,
            "order_hex": hex128(order.to_bits()),
            "fill_hex": hex128(fill.to_bits()),
            "is_filled": fill.is_filled,
            "fill_price_hex": hex32(fill.fill_price),
            "fill_qty": fill.fill_qty,
        })
    with open(os.path.join(out_dir, "exchange_vectors.json"), "w") as f:
        json.dump(exchange_vectors, f, indent=2)
    print(f"  {len(exchange_vectors)} exchange vectors written")

    # ──────────────────────────────────────────────────────────
    # Summary
    # ──────────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"All vectors written to: {os.path.abspath(out_dir)}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
