# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/constraints/hft_top.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ps_0 || ORIG_REF_NAME==system_zynq_ps_0} -quiet] -quiet

# IP: bd/system/ip/system_hft_core_0/system_hft_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hft_core_0 || ORIG_REF_NAME==system_hft_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sc_0/system_axi_sc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_sc_0 || ORIG_REF_NAME==system_axi_sc_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_sys_0/system_rst_sys_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_sys_0 || ORIG_REF_NAME==system_rst_sys_0} -quiet] -quiet

# XDC: c:/Users/Kushal Agrawal/UW-madison school work/Dual-FPGA-Trading-Engine/vivado/hft_board_b/hft_board_b.gen/sources_1/bd/system/system_ooc.xdc
